### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by sabas** [openterrain/openterrain#3]
What about adopting a workflow like OpenAddresses to collect the data sources? https://github.com/openaddresses/openaddresses

**Comment by iandees** [comment]
I would be happy to give an overview of how OA works. Just shoot me an e-mail if you'd like to know more or if you have any questions.

**Comment by sethfitz** [comment]
We're using something similar.  The guts of it are currently in the [Vapor Clock](https://github.com/stamen/vapor-clock) repo, but I've got it in pieces in the garage at the moment and am working on moving from using SQS to SWF (Simple Workflow) to back it, since it's truly a workflow rather than a set of discrete tasks.

I've been following Nelson's experiences with OA on his dev blog, so pretty much everything I know is from there.  A few key differences:
- we're ingesting source data into S3 as an initial step (if it's not already available in an S3 bucket) in order to reduce latency (and load on the sources) when processing (we assume that the source data rarely changes)
- tasks are intended to run discretely (and thus be horizontally distributed) within the overall workflow; there's a CloudFormation configuration in the Vapor Clock repo that uses CloudWatch to spin up spot instances as necessary
- there's minimal custom code--it's generally all glue around the GDAL command line utilities
- it uses Node.js to manage sub-processes

Once I get the SWF pieces re-assembled, expect a blog post about how everything fits together.
